---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.497.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: nodejs/node
  version: v24.15.0 # renovate: datasource=github-releases depName=nodejs/node
- name: pnpm/pnpm@v10.33.1
- name: biomejs/biome@cli/v1.9.4
- name: google/yamlfmt@v0.21.0
- name: tamasfe/taplo@0.10.0
- name: evilmartians/lefthook@v2.1.6
- name: rhysd/actionlint@v1.7.12
- name: suzuki-shunsuke/ghalint@v1.5.5
- name: suzuki-shunsuke/pinact@v3.9.0
- name: editorconfig-checker/editorconfig-checker@v3.6.1
- name: oxc-project/oxc/oxlint@oxlint_v0.16.0
