---
name: Setup Aqua
description: Setup Aqua by using cache and environment variables
runs:
  using: composite
  steps:
  - name: Restore Aqua Cache
    id: cache-primes-restore
    uses: actions/cache/restore@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
    with:
      key: aqua-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/.aqua.yml') }}
      path: |-
        ~/.local/share/aquaproj-aqua
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
    with:
      aqua_version: v2.60.1
      aqua_opts: -a
  - name: Get Default Branch
    id: gh
    env:
      GH_TOKEN: ${{ github.token }}
    shell: bash
    run: echo default_branch_ref_name="$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)" >> "$GITHUB_OUTPUT"
  - name: Show Branch
    shell: bash
    run: |-
      echo "REF_NAME: '${REF_NAME}'"
      echo "DEFAULT_BRANCH: '${DEFAULT_BRANCH}'"
    env:
      REF_NAME: ${{ github.ref_name }}
      DEFAULT_BRANCH: ${{ steps.gh.outputs.default_branch_ref_name }}
  - name: Save Aqua Cache
    if: github.ref_name == steps.gh.outputs.default_branch_ref_name && steps.cache-primes-restore.outputs.cache-hit != 'true'
    uses: actions/cache/save@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
    with:
      key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
      path: |-
        ~/.local/share/aquaproj-aqua
