// GitHub Apps API playground worker — returns the installation's repository list as JSON.

import { App } from "@octokit/app";
import { Hono } from "hono";
import { bearerAuth } from "hono/bearer-auth";

// worker-configuration.d.ts is generated by `wrangler types` and doesn't know
// about this optional secret, so it's declared here via module augmentation.
declare global {
	interface Env {
		API_TOKEN?: string;
	}
}

const app = new Hono<{ Bindings: Env }>();

// Auth is opt-in: only enforced when a deployment configures API_TOKEN, so the
// playground stays usable out of the box without a secret. When set, requests
// must send `Authorization: Bearer <API_TOKEN>`.
app.use("*", async (c, next) => {
	if (!c.env.API_TOKEN) {
		return next();
	}
	return bearerAuth<{ Bindings: Env }>({
		token: c.env.API_TOKEN,
		noAuthenticationHeader: { message: { error: "Unauthorized" } },
		invalidAuthenticationHeader: { message: { error: "Unauthorized" } },
		invalidToken: { message: { error: "Unauthorized" } },
	})(c, next);
});

// Any path/method that isn't handled below returns a JSON 404.
app.notFound((c) => c.json({ error: "Not Found" }, 404));

app.get("/", async (c) => {
	const env = c.env;

	const missing: string[] = [];
	if (!env.APP_ID) missing.push("APP_ID");
	if (!env.PRIVATE_KEY) missing.push("PRIVATE_KEY");
	if (!env.INSTALLATION_ID) missing.push("INSTALLATION_ID");

	if (missing.length > 0) {
		return c.json({ error: "Missing required configuration", missing }, 400);
	}

	const octokitApp = new App({
		appId: env.APP_ID,
		privateKey: env.PRIVATE_KEY,
	});

	const installationId = Number(env.INSTALLATION_ID);
	if (Number.isNaN(installationId)) {
		return c.json({ error: "Invalid INSTALLATION_ID" }, 400);
	}

	try {
		const installationOctokit =
			await octokitApp.getInstallationOctokit(installationId);

		const { data } = await installationOctokit.request(
			"GET /installation/repositories",
		);

		return c.json(data);
	} catch (error) {
		console.error(error);
		const message = error instanceof Error ? error.message : "Unknown error";
		return c.json({ error: message }, 502);
	}
});

export default app;
