---
name: CI
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: ./.github/actions/setup-aqua
    - name: Setup pnpm
      uses: ./.github/actions/setup-pnpm
    - name: Running Typecheck
      run: pnpm run typecheck
    - name: Running Lint
      run: pnpm run lint
    - name: Running Test
      run: pnpm run test
